-- supabase-schema.sql

-- Users (Telegram users)
CREATE TABLE users (
  telegram_id BIGINT PRIMARY KEY,
  first_name TEXT,
  last_name TEXT,
  username TEXT,
  wallet_address TEXT,          -- TON wallet for receiving earnings
  role TEXT DEFAULT 'user' CHECK (role IN ('user','owner','admin')),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Channels / Groups registered by owners
CREATE TABLE channels (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id BIGINT REFERENCES users(telegram_id) ON DELETE CASCADE,
  channel_name TEXT NOT NULL,
  channel_chat_id BIGINT,       -- Telegram chat id (for bot management)
  channel_invite_link TEXT,     -- Permanent invite link (generated by bot)
  subscription_price NUMERIC(12,9) NOT NULL CHECK (subscription_price > 0), -- in TON
  duration_days INTEGER NOT NULL CHECK (duration_days > 0),
  is_active BOOLEAN DEFAULT true,
  auto_renewal_reminders BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Subscriptions
CREATE TABLE subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id BIGINT REFERENCES users(telegram_id) ON DELETE CASCADE,
  channel_id UUID REFERENCES channels(id) ON DELETE CASCADE,
  start_date TIMESTAMPTZ DEFAULT now(),
  end_date TIMESTAMPTZ NOT NULL,
  transaction_hash TEXT,        -- TON tx hash of payment
  amount NUMERIC(12,9),
  status TEXT DEFAULT 'active' CHECK (status IN ('active','expired','cancelled')),
  auto_renew BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Platform transactions (split tracking)
CREATE TABLE platform_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  subscription_id UUID REFERENCES subscriptions(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES users(telegram_id),
  channel_id UUID REFERENCES channels(id),
  channel_owner_id BIGINT REFERENCES users(telegram_id),
  amount_total NUMERIC(12,9),
  owner_share NUMERIC(12,9),   -- 99%
  platform_fee NUMERIC(12,9),  -- 1%
  transaction_hash TEXT,       -- original payment tx hash
  owner_paid_out BOOLEAN DEFAULT false,
  paid_out_tx_hash TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Withdrawal requests
CREATE TABLE withdrawals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_owner_id BIGINT REFERENCES users(telegram_id) ON DELETE CASCADE,
  amount NUMERIC(12,9) NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','processed')),
  request_date TIMESTAMPTZ DEFAULT now(),
  processed_date TIMESTAMPTZ,
  payout_tx_hash TEXT,
  admin_notes TEXT
);

-- Reports against channels
CREATE TABLE reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reporter_id BIGINT REFERENCES users(telegram_id) ON DELETE CASCADE,
  reported_channel_id UUID REFERENCES channels(id) ON DELETE CASCADE,
  reason TEXT NOT NULL,         -- e.g. scam, inappropriate, insult, racism, other
  description TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','reviewed','resolved')),
  reviewed_by BIGINT REFERENCES users(telegram_id),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Reviews / Ratings
CREATE TABLE reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id BIGINT REFERENCES users(telegram_id) ON DELETE CASCADE,
  channel_id UUID REFERENCES channels(id) ON DELETE CASCADE,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Row Level Security (RLS) to protect data when using Supabase client directly
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE withdrawals ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

-- Users can read/update their own row
CREATE POLICY "Users can view own record" ON users FOR SELECT USING (telegram_id = current_setting('request.jwt.claims', true)::json->>'telegram_id');
CREATE POLICY "Users can update own record" ON users FOR UPDATE USING (telegram_id = current_setting('request.jwt.claims', true)::json->>'telegram_id');

-- Channel owners can read/update their own channels
CREATE POLICY "Owners manage own channels" ON channels FOR ALL USING (owner_id = current_setting('request.jwt.claims', true)::json->>'telegram_id');

-- Anyone (authenticated) can read active channels (for purchase page)
CREATE POLICY "Anyone can view active channels" ON channels FOR SELECT USING (is_active = true);

-- Subscriptions: users can see their own
CREATE POLICY "Users see own subscriptions" ON subscriptions FOR SELECT USING (user_id = current_setting('request.jwt.claims', true)::json->>'telegram_id');

-- Platform transactions: owners can see their own, admin all
CREATE POLICY "Owners view own transactions" ON platform_transactions FOR SELECT USING (channel_owner_id = current_setting('request.jwt.claims', true)::json->>'telegram_id');

-- Withdrawals: owners see own, admin all
CREATE POLICY "Owners view own withdrawals" ON withdrawals FOR SELECT USING (channel_owner_id = current_setting('request.jwt.claims', true)::json->>'telegram_id');

-- Reports: reporter can see own, admin all
CREATE POLICY "Reporter sees own reports" ON reports FOR SELECT USING (reporter_id = current_setting('request.jwt.claims', true)::json->>'telegram_id');

-- Reviews: anyone can read, users can create their own (via backend)
CREATE POLICY "Anyone can read reviews" ON reviews FOR SELECT USING (true);
CREATE POLICY "Users create own reviews" ON reviews FOR INSERT WITH CHECK (user_id = current_setting('request.jwt.claims', true)::json->>'telegram_id');